package dev.pranay.chronos.scheduler;

import dev.pranay.chronos.domain.MisfirePolicy;
import dev.pranay.chronos.domain.Schedule;
import dev.pranay.chronos.domain.ScheduleType;
import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Cron arithmetic, including the two days a year that break naive implementations.
 *
 * <p>Pure logic, no Spring, no container. The DST cases in particular are worth pinning here
 * rather than discovering in production, because they are unobservable for months at a time and
 * then wrong by an hour.
 */
class CronCalculatorTest {

    private static final ZoneId CHICAGO = ZoneId.of("America/Chicago");
    private final CronCalculator calculator = new CronCalculator();

    // ---------------------------------------------------------------- basic advancement

    @Test
    void computesTheNextDailyOccurrence() {
        Schedule daily = cron("0 0 9 * * *", "America/Chicago");
        Instant base = chicago(2026, 6, 15, 9, 0);

        Instant next = calculator.nextExecution(daily, base, base);

        assertThat(next).isEqualTo(chicago(2026, 6, 16, 9, 0));
    }

    /**
     * A daily 09:00 job stays at 09:00 <em>local</em> across a DST change.
     *
     * <p>This is the test that catches computing in UTC. 09:00 America/Chicago is 14:00 UTC in
     * winter and 15:00 UTC in summer; anything that precomputes the series as fixed UTC instants
     * drifts by an hour twice a year while looking perfectly correct in between.
     */
    @Test
    void aDailyJobKeepsItsLocalTimeAcrossTheSpringForwardBoundary() {
        Schedule daily = cron("0 0 9 * * *", "America/Chicago");

        // 2026 US spring forward: Sunday 8 March.
        Instant beforeChange = chicago(2026, 3, 7, 9, 0);
        Instant next = calculator.nextExecution(daily, beforeChange, beforeChange);

        assertThat(next.atZone(CHICAGO).getHour())
                .as("must still be 09:00 local the day the clocks move")
                .isEqualTo(9);
        assertThat(next).isEqualTo(chicago(2026, 3, 8, 9, 0));

        // And the gap really was 23 hours, which is what proves the zone was applied.
        assertThat(Duration.between(beforeChange, next))
                .as("the day the clocks spring forward is 23 hours long")
                .isEqualTo(Duration.ofHours(23));
    }

    @Test
    void aDailyJobKeepsItsLocalTimeAcrossTheFallBackBoundary() {
        Schedule daily = cron("0 0 9 * * *", "America/Chicago");

        // 2026 US fall back: Sunday 1 November.
        Instant beforeChange = chicago(2026, 10, 31, 9, 0);
        Instant next = calculator.nextExecution(daily, beforeChange, beforeChange);

        assertThat(next.atZone(CHICAGO).getHour()).isEqualTo(9);
        assertThat(Duration.between(beforeChange, next))
                .as("the day the clocks fall back is 25 hours long")
                .isEqualTo(Duration.ofHours(25));
    }

    /**
     * A job scheduled inside the spring-forward gap is skipped that day.
     *
     * <p>02:30 does not exist on 8 March 2026 in Chicago, and {@code CronExpression} steps straight
     * past it to the 9th. That is the documented policy rather than an accident: the user asked for
     * 02:30, and firing at 03:30 instead would invent an instant they never specified. The
     * alternative bias — inventing a time — risks a duplicate against anything that also fires in
     * the resumed hour.
     *
     * <p>Written down and asserted because it is invisible for 364 days a year.
     */
    @Test
    void aJobInsideTheSpringForwardGapIsSkippedForThatDay() {
        Schedule daily = cron("0 30 2 * * *", "America/Chicago");
        Instant dayBefore = chicago(2026, 3, 7, 2, 30);

        Instant next = calculator.nextExecution(daily, dayBefore, dayBefore);
        ZonedDateTime local = next.atZone(CHICAGO);

        assertThat(local.toLocalDate())
                .as("02:30 doesn't exist on the 8th, so the next real occurrence is the 9th")
                .isEqualTo(java.time.LocalDate.of(2026, 3, 9));
        assertThat(local.getHour()).isEqualTo(2);
        assertThat(local.getMinute()).isEqualTo(30);
    }

    /**
     * A job in the fall-back overlap fires once, at the first occurrence.
     *
     * <p>01:30 happens twice on 1 November — once at CDT and again an hour later at CST — and
     * {@code CronExpression} returns <em>both</em>. Left alone that is a duplicate delivery
     * generated by the calendar rather than by any failure, and one the receiver's idempotency key
     * cannot absorb, since the two firings genuinely have different scheduled times.
     *
     * <p>{@code CronCalculator} detects the repeat by its identical local wall-clock time and skips
     * it, so the job fires once at the earlier offset. This test is the reason that code exists.
     */
    @Test
    void aJobInsideTheFallBackOverlapFiresOnceNotTwice() {
        Schedule daily = cron("0 30 1 * * *", "America/Chicago");
        Instant dayBefore = chicago(2026, 10, 31, 1, 30);

        Instant first = calculator.nextExecution(daily, dayBefore, dayBefore);
        ZonedDateTime local = first.atZone(CHICAGO);

        assertThat(local.toLocalDate()).isEqualTo(java.time.LocalDate.of(2026, 11, 1));
        assertThat(local.getHour()).isEqualTo(1);
        assertThat(local.getMinute()).isEqualTo(30);
        assertThat(local.getOffset())
                .as("the earlier of the two possible offsets — CDT, before the clocks go back")
                .isEqualTo(java.time.ZoneOffset.ofHours(-5));

        // The occurrence after it must be the following day, NOT the 01:30 repeat an hour later.
        Instant second = calculator.nextExecution(daily, first, first);
        assertThat(second.atZone(CHICAGO).toLocalDate())
                .as("the repeated 01:30 must have been skipped, or this job fires twice that night")
                .isEqualTo(java.time.LocalDate.of(2026, 11, 2));
    }

    @Test
    void differentZonesProduceDifferentInstantsForTheSameExpression() {
        Instant base = Instant.parse("2026-06-15T00:00:00Z");
        Instant chicagoNext = calculator.nextExecution(cron("0 0 9 * * *", "America/Chicago"), base, base);
        Instant tokyoNext = calculator.nextExecution(cron("0 0 9 * * *", "Asia/Tokyo"), base, base);

        assertThat(chicagoNext)
                .as("the timezone is load-bearing; dropping it would make these identical")
                .isNotEqualTo(tokyoNext);
    }

    // ---------------------------------------------------------------- misfire policy

    /**
     * FIRE_ONCE collapses a backlog into a single catch-up run.
     *
     * <p>An hourly job that was unreachable for six hours should produce one report on recovery,
     * not six. The alternative floods the receiver with a burst of stale firings at exactly the
     * moment the system is coming back up.
     */
    @Test
    void fireOnceSkipsPastEveryMissedOccurrence() {
        Schedule hourly = cron("0 0 * * * *", "UTC", MisfirePolicy.FIRE_ONCE);
        Instant lastFired = Instant.parse("2026-06-15T03:00:00Z");
        Instant now = Instant.parse("2026-06-15T09:30:00Z");   // six hours of downtime

        Instant next = calculator.nextExecution(hourly, lastFired, now);

        assertThat(next)
                .as("one catch-up run at the next future slot, not six replays")
                .isEqualTo(Instant.parse("2026-06-15T10:00:00Z"));
    }

    /** FIRE_ALL replays the backlog one occurrence at a time. */
    @Test
    void fireAllReturnsTheNextMissedOccurrenceSoTheBacklogIsWorkedThrough() {
        Schedule hourly = cron("0 0 * * * *", "UTC", MisfirePolicy.FIRE_ALL);
        Instant lastFired = Instant.parse("2026-06-15T03:00:00Z");
        Instant now = Instant.parse("2026-06-15T09:30:00Z");

        Instant next = calculator.nextExecution(hourly, lastFired, now);

        assertThat(next)
                .as("the immediate next slot, still in the past — it fires now and rolls again")
                .isEqualTo(Instant.parse("2026-06-15T04:00:00Z"));
    }

    /**
     * Rolling forward from the scheduled time does not let retry delay consume a slot.
     *
     * <p>This is the A6 regression in miniature. A 5-minutely job scheduled for 09:05 that only
     * succeeds at 09:06:30 must still compute 09:10. Rolling from the actual run time would give
     * 09:10 here too — but the moment a retry pushes past a boundary, the run time and the
     * scheduled time diverge and slots start disappearing with nothing recording it.
     */
    @Test
    void rollingForwardUsesTheScheduledTimeNotTheActualRunTime() {
        Schedule everyFive = cron("0 */5 * * * *", "UTC");
        Instant scheduledFor = Instant.parse("2026-06-15T09:05:00Z");
        Instant actuallyRanAt = Instant.parse("2026-06-15T09:06:30Z");

        Instant fromScheduled = calculator.nextExecution(everyFive, scheduledFor, actuallyRanAt);

        assertThat(fromScheduled).isEqualTo(Instant.parse("2026-06-15T09:10:00Z"));
    }

    // ---------------------------------------------------------------- validation

    @Test
    void invalidExpressionsAreRejectedWithAUsefulMessage() {
        assertThatThrownBy(() -> calculator.parse("not a cron"))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("Invalid cron expression")
                .hasMessageContaining("6 fields");

        assertThatThrownBy(() -> calculator.parse(null))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> calculator.parse("  "))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void aValidExpressionParses() {
        assertThat(calculator.parse("0 0 9 * * *")).isNotNull();
        assertThat(calculator.parse(" 0 */5 * * * * ")).isNotNull();
    }

    // ---------------------------------------------------------------- helpers

    private static Schedule cron(String expression, String zone) {
        return cron(expression, zone, MisfirePolicy.FIRE_ONCE);
    }

    private static Schedule cron(String expression, String zone, MisfirePolicy policy) {
        return new Schedule(ScheduleType.CRON, null, expression, zone, policy);
    }

    private static Instant chicago(int year, int month, int day, int hour, int minute) {
        return ZonedDateTime.of(LocalDateTime.of(year, month, day, hour, minute), CHICAGO).toInstant();
    }
}
